const {StyleSheet} = require('react-native');

export const style = StyleSheet.create({
  main: {
    flex: 1,
  },
  bgTitle: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 4,
  },
  textTitle: {
    fontSize: 32,
    color: 'black',
    fontWeight: '500',
  },
  containerListCart: {flex: 1, alignItems: 'center'},
  insideContainerListCart: {
    backgroundColor: 'white',
    width: '90%',
    height: 100,
    marginTop: 20,
    alignItems: 'center',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 4,
  },
  imageListCart: {width: 80, height: 80},
  containerInforCart: {height: 80, width: 80},
  containerName: {height: 50, width: 80},
  textInforCart: {fontSize: 16, color: 'black', fontWeight: '500'},
  containerPrice: {height: 30, width: 80},
  containerInDe: {
    height: 80,
    width: 100,
    justifyContent: 'space-around',
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 5,
  },
  containerDecrement: {
    width: 30,
    height: 30,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerNumberItem: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerIncrement: {
    width: 30,
    height: 30,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerBtnRemove: {
    height: 80,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnRemove: {
    borderWidth: 1,
    width: 65,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerOrder: {
    position: 'absolute',
    width: '100%',
    height: 50,
    bottom: 0,
    flexDirection: 'row',
  },
  totalPrice: {
    flex: 2,
    backgroundColor: 'green',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  textOrder: {fontSize: 24, color: 'white', fontWeight: '500'},
  btnOrder: {
    flex: 1,
    backgroundColor: 'blue',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
